# Generated by Django 4.2.6 on 2023-11-16 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='apellido')),
                ('user_name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='usuario')),
                ('birth_date', models.DateField(null=True, verbose_name='fecha de nacimiento')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=300, verbose_name='logro')),
                ('date', models.DateField(verbose_name='fecha')),
                ('idarea', models.IntegerField(default=0, verbose_name='id area')),
                ('description', models.CharField(max_length=500, verbose_name='descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logros/files/image_achievement', verbose_name='imagen')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id user')),
            ],
            options={
                'db_table': 'Achievements',
            },
        ),
    ]
