# Generated by Django 4.2.6 on 2023-11-18 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='', verbose_name='imagen perfil')),
                ('bio', models.CharField(max_length=300, verbose_name='biografia')),
                ('iduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id user')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
