# Generated by Django 4.2.6 on 2023-11-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_achievements/', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='image_profile/', verbose_name='imagen perfil'),
        ),
    ]
